# Inteligencia Artificial

La brecha digital mundial y nacional ha alcanzado todas las ciencias; las ciencias médicas particularmente han llegado a ser una simbiosis productiva con la tecnología. Desde la ortopedia con el uso de prótesis de materiales más resistentes, hasta el uso de dispositivos y aplicaciones para el seguimiento y autocontrol en diferentes padecimientos. Además, en los últimos años, la mejora en el análisis de datos médicos para la interpretación de diagnósticos más efectivos y eficientes, así como de los generados en los hospitales. Este análisis de grandes datos (big data, por sus siglas en inglés), sólo es posible con el uso de la Inteligencia Artificial (AI, Artificial Intelligence, por sus siglas en inglés). Los datos masivos también incluyen conjuntos de datos específicos con tamaños y complejidades elevados que requieren técnicas algorítmicas nuevas para extraer de ellos información útil. Los datos en todas sus formas, poseen el potencial de proporcionar un caudal de información útil siempre que se logre desarrollar el modo de extraerla (Alsina, 2017). Las técnicas nuevas combinan la estadística tradicional con la informática y hacen cada vez más viable el análisis de grandes volúmenes de datos. Estas técnicas y algoritmos desarrollados por especialistas en estadística e informática, buscan patrones en los datos. La clave del éxito en análisis de datos masivos radica en determinar qué patrones son los relevantes (Nin Guerrero, 2019). El advenimiento de la era digital conlleva cambios que alteran de un modo sustancial la manera de recopilar los datos, almacenarlos y analizarlos.

La IA utiliza diferentes métodos de aprendizaje automático (machine learning, por sus siglas en inglés); tipos de algoritmos y sus características básicas que pueden clasificarse de la siguiente manera:

Métodos de Inteligencia Artificial.